### ISSUE TITLE
How to customise service name?

### ISSUE THREAD

**Issue by ghost** [nopnop2002/esp-idf-uart2bt#2]
Hi nopnop2002, thank you very much for this project. Could you help me edit the source files? Thank you

**Comment by SlitheringMule** [comment]
@nopnop2002 I would like to chance the service names to nordic UART profile so I can use it on iOS apps please
```
/*
Bluetooth LE GATT UUIDs for the Nordic UART profile
*/
const char *BLE_SERIAL_SERVICE_UUID = "6e400001-b5a3-f393-e0a9-e50e24dcca9e";
const char *BLE_RX_UUID = "6e400002-b5a3-f393-e0a9-e50e24dcca9e";
const char *BLE_TX_UUID = "6e400003-b5a3-f393-e0a9-e50e24dcca9e";
```

**Comment by SlitheringMule** [comment]
```
   warning: conversion from 'long long unsigned int' to 'uint16_t' {aka 'const short unsigned int'}
   81 | #define ESP_GATT_UUID_SPP_DATA_NOTIFY           0x6e400003b5a3f393e0a9e50e24dcca9e; //0xABF2
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by nopnop2002** [comment]
I don't have iOS so I don't know.

**Comment by SlitheringMule** [comment]
Do you know how to change all uuids to 128-bit?

**Comment by nopnop2002** [comment]
i don't know.
You may be able to find out by asking here.
https://github.com/espressif/esp-idf/issues

**Comment by SlitheringMule** [comment]
Okay thanks for replying <3

**Comment by SlitheringMule** [comment]
Solved it https://github.com/espressif/esp-idf/issues/11621#issuecomment-1582364102, but sending data from BLE to Serial doesn't work

**Comment by SlitheringMule** [comment]
I can manually send data out of the hardware UART TX if I hard-code it, but can't send any data over Bluetooth

**Comment by SlitheringMule** [comment]
I don't think it is correctly receiving data over bluetooth

**Comment by SlitheringMule** [comment]
I see the
```
gatts_profile_event_handler: ESP_GATTS_WRITE_EVT, write value:
gatts_profile_event_handler: 59 65 73 0a
```
but I don't get any logs from the
```
xQueueReceive(xQueueUart, &cmdBuf, portMAX_DELAY);
ESP_LOGD(pcTaskGetName(NULL), "cmdBuf.length=%d", cmdBuf.length);
ESP_LOG_BUFFER_HEXDUMP(pcTaskGetName(NULL), cmdBuf.payload, cmdBuf.length, ESP_LOG_DEBUG);
```
part of the code in `static void uart_tx_task(void* pvParameters)`
However I am sure `uart_tx_task` is being run as I can see it executes code at the start of the function

**Comment by SlitheringMule** [comment]
```cpp
static void uart_tx_task(void* pvParameters)
{
	ESP_LOGI(pcTaskGetName(NULL), "Start using GPIO%d", CONFIG_UART_TX_GPIO);
	CMD_t cmdBuf;
	//cmdBuf.command = CMD_BLUETOOTH_DATA; // Added, idk if it's needed

	char sample[4] = "ABCD";
	uart_write_bytes(UART_NUM_1, sample, 4);
	while(1) {
		ESP_LOGI(__FUNCTION__, "1 ##########################");
		xQueueReceive(xQueueUart, &cmdBuf, portMAX_DELAY);
		ESP_LOGI(__FUNCTION__, "2 ##########################");
		ESP_LOGD(pcTaskGetName(NULL), "cmdBuf.length=%d", cmdBuf.length);
		ESP_LOGI(__FUNCTION__, "3 ##########################");
		ESP_LOG_BUFFER_HEXDUMP(pcTaskGetName(NULL), cmdBuf.payload, cmdBuf.length, ESP_LOG_DEBUG);
		ESP_LOGI(__FUNCTION__, "4 ##########################");
		int txBytes = uart_write_bytes(UART_NUM_1, cmdBuf.payload, cmdBuf.length);
		ESP_LOGI(__FUNCTION__, "5 ##########################");
		ESP_LOGI(pcTaskGetName(NULL), "txBytes=%d", txBytes);
		ESP_LOGI(__FUNCTION__, "6 ##########################");
	}

	// Never reach here
	vTaskDelete(NULL);
}
```

In the monitor I get `Start using GPIO` and `1 ##################` but never `2 ############`, is there a bug?

**Comment by nopnop2002** [comment]
Since xQueueUart is a Queue handle, it will block until another task writes to the Queue.

**Comment by SlitheringMule** [comment]
> Since xQueueUart is a Queue handle, it will block until another task writes to the Queue.

Thank you! Makes sense now, the code wasn't adding anything to the TX queue.
To fix it I added
```cpp
cmdBuf.command = CMD_BLUETOOTH_DATA;
xQueueSend(xQueueMain, &cmdBuf, 0);
```
in the `ESP_GATTS_WRITE_EVT` `case` in the `gatts_profile_event_handler` function
However, I only get `0xff` as my output.

How did the code work for you if there is no sending of the received bluetooth data to the UART TX?

**Comment by SlitheringMule** [comment]
I am looking in your bluetooth classic example and see you did
```
strcpy((char *)cmdBuf.payload, (char *)param->data_ind.data);
cmdBuf.payload[param->data_ind.len] = 0;
cmdBuf.length = param->data_ind.len;
```
but of course it isn't BLE compatible. I wasn't aware that only your Classic BT was functioning, I thought both worked!

**Comment by SlitheringMule** [comment]
Nevermind it's not, it causes a crash

**Comment by SlitheringMule** [comment]
It's `write` but I get crashes when it's a long message, also it's slow
